import 'package:flutter/material.dart';

final List collegeOptions = [
  'Amherst College',
  'Babson College',
  'Barnard College',
  'Bates College',
  'Binghamton University, SUNY',
  'Boston College',
  'Boston University',
  'Bowdoin College',
  'Brigham Young University',
  'Brown University',
  'Bucknell University',
  'California Institute of Technology',
  'California Polytechnic State University, San Luis Obispo',
  'California State University, Fullerton',
  'California State University, Long Beach',
  'Carnegie Mellon University',
  'Claremont McKenna College',
  'Clemson University',
  'Colgate University',
  'Columbia University',
  'Cooper Union',
  'Cornell University',
  'CUNY, Baruch College',
  'Dartmouth College',
  'Davidson College',
  'Duke University',
  'Emory University',
  'Florida State University',
  'Franklin W Olin College of Engineering',
  'George Washington University',
  'Georgetown University',
  'Georgia Institute of Technology',
  'Grinnell College',
  'Hamilton College',
  'Harvard University',
  'Haverford College',
  'Indiana University, Bloomington',
  'Johns Hopkins University',
  'Lafayette College',
  'Lehigh University',
  'Massachusetts Institute of Technology',
  'Michigan State University',
  'Middlebury College',
  'New York University',
  'North Carolina State University, Raleigh',
  'Northeastern University',
  'Northwestern University',
  'Ohio State University',
  'Pomona College',
  'Princeton University',
  'Purdue University',
  'Rice University',
  'Rutgers University',
  'San Diego State University',
  'Santa Clara University',
  'Southern Methodist University',
  'Stanford University',
  'Stony Brook University, SUNY',
  'Swarthmore College',
  'Texas A&M University, College Station',
  'Trinity College (CT)',
  'Trinity University (TX)',
  'Tufts University',
  'University of California, Berkeley',
  'University of California, Davis',
  'University of California, Irvine',
  'University of California, Los Angeles',
  'University of California, Merced',
  'University of California, Riverside',
  'University of California, San Diego',
  'University of California, San Francisco',
  'University of California, Santa Barbara',
  'University of California, Santa Cruz',
  'University of Chicago',
  'University of Connecticut',
  'University of Florida',
  'University of Georgia',
  'University of Illinois, Urbana-Champaign',
  'University of Maryland, College Park',
  'University of Miami (FL)',
  'University of Michigan, Ann Arbor',
  'University of Minnesota, Twin Cities',
  'University of North Carolina, Chapel Hill',
  'University of Notre Dame',
  'University of Pennsylvania',
  'University of Rochester',
  'University of Southern California',
  'University of Texas, Austin',
  'University of Utah',
  'University of Virginia',
  'University of Washington, Seattle',
  'University of Wisconsin, Madison',
  'Vanderbilt University',
  'Villanova University',
  'Virginia Tech',
  'Wake Forest University',
  'Washington and Lee University',
  'Washington University in St. Louis',
  'Wellesley College',
  'Wesleyan University',
  'William & Mary',
  'Williams College',
  'Yale University'
];