import 'package:flutter/material.dart';

final List majorOptions = [
  'Accounting',
  'Agriculture',
  'Animal Science',
  'Anthropology',
  'Arabic',
  'Architecture',
  'Biochemistry',
  'Biology',
  'Business Administration',
  'Business Management',
  'Chemical Engineering',
  'Chemistry',
  'Civil Engineering',
  'Communications',
  'Computer Engineering',
  'Computer Science',
  'Counseling',
  'Criminal Justice',
  'Criminology',
  'Economics',
  'Education',
  'Electrical Engineering',
  'English',
  'Environmental Science',
  'Film',
  'Finance',
  'Forensic Science',
  'Graphic Design',
  'History',
  'Hospitality',
  'Interior Design',
  'International Relations',
  'Italian',
  'Journalism',
  'Kinesiology',
  'Marine Biology',
  'Marketing',
  'Mathematics',
  'Mechanical Engineering',
  'Music',
  'Neuroscience',
  'Nursing',
  'Nutrition',
  'Pharmacy',
  'Photography',
  'Physics',
  'Politics',
  'Pre-law',
  'Psychology',
  'Public Relations',
  'Robotics',
  'Social Work',
  'Sociology',
  'Spanish',
  'Theology',
  'Zoology',
];